/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
  id INT GENERATED BY DEFAULT AS IDENTITY,
   name varchar(100),
   date_of_birth  date     NOT NULL,
   escape_attempts int,
   neutered BOOLEAN,
   weight_kg         DEC,
   PRIMARY KEY (id)
);


-- Add New Column Species

ALTER TABLE animals
ADD species varchar(100);


-- Create New Table Owners

CREATE TABLE owners(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(50),
  age INT,
  PRIMARY KEY (id)
);

-- Create New Table Species

CREATE TABLE species(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50),
  PRIMARY KEY (id)
);

-- Remove column species from animals

ALTER TABLE animals
DROP COLUMN species;

-- Add column `species_id` which is a foreign key referencing `species` table

ALTER TABLE animals
ADD species_id INT;
ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species(id);

-- Add column `owner_id` which is a foreign key referencing the `owners` table

ALTER TABLE animals
ADD owner_id INT;
ALTER TABLE animals 
ADD FOREIGN KEY (owner_id) REFERENCES owners(id);
